In [8]:
import numpy as np # import numpy library np is an alias

In [9]:
import numpy as np # import numpy library np is an alias
# Create an array of student scores
scores = np.array([
    [89, 85, 92],  # Scores for John
    [95, 90, 90],  # Scores for Anna
    [78, 92, 85],  # Scores for Peter
    [92, 88, 95],  # Scores for Linda
    [88, 86, 95]   # Scores for Mike
])

print(scores)

[[89 85 92]
 [95 90 90]
 [78 92 85]
 [92 88 95]
 [88 86 95]]


In [10]:
averages = np.mean(scores, axis=1)
print(averages) 

[88.66666667 91.66666667 85.         91.66666667 89.66666667]


In [ ]:
top_student_index = np.argmax(averages)
print(top_student_index)  # Output: 1 (assuming Anna is the first student with the highest average)

In [ ]:
math_above_90 = scores[:, 0] > 90  # Scores for Math are in the first column
print(math_above_90)  # Output: [False  True False  True False]